using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace OTT_Platform.Migrations
{
    public partial class Movieautogeneratedidentityremoved : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {

        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
